### ISSUE TITLE
TMDB blurry when extension fails to load

### ISSUE THREAD

**Issue by costaht** [RemiRigal/Overseerr-Assistant#18]
When the extension fails to connect to Overseerr, it prevents TMDB from loading completely.
I don't see any error in the console related to the extension, so the only things I can provide are these screenshots:

**Loading forever**

![Screenshot from 2022-06-18 01-27-51](https://user-images.githubusercontent.com/50637431/174424420-829b2bd1-1746-419f-b7ca-05fc3d3125c7.png)

**When I click on the poster, the whole page goes blurry, as if the CSS isn't loading correctly.**

![Screenshot from 2022-06-18 01-32-57](https://user-images.githubusercontent.com/50637431/174424419-2c288f28-b79e-4938-9dea-e042e41c4648.png)

**Comment by seanecoffey** [comment]
I think this is actually a product of the way the extension currently loads the entire overseerr CSS file, so it includes references to classes other than just the overseerr assistant icons
This is causing issues on other sites too (letterboxd).  I think ideally the specific CSS needs to be isolated and given unique class names etc. so that it only applies to the overseerr assistant elements.

**Comment by RemiRigal** [comment]
@seanecoffey you are absolutely right ! Improving the stylesheet has been on my roadmap for a while now, but I have been busy with other things. I will try to do this in the next few days ! Thank you for reporting this.

**Comment by costaht** [comment]
Just tested all sorts of scenarios and now it works perfectly
Thanks a lot
